version: "2"

linters-settings:
  depguard:
    rules:
      main:
        list-mode: lax
        files:
          - $all
        allow:
          - $gostd
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16"
          - pkg: "github.com/sirupsen/logrus"
            desc: "use log/slog"
          - pkg: "github.com/rs/zerolog"
            desc: "use log/slog"
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    settings:
      hugeParam:
        sizeThreshold: 512
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  mnd:
    checks:
      - argument
      - case
      - condition
      - return
    ignored-numbers:
      - '0'
      - '1'
      - '2'
      - '3'
      - '4'
      - '5'
      - '0o6'
    ignored-functions:
      - strings.SplitN
  lll:
    line-length: 140
  nakedret:
    max-func-lines: 75
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

linters:
  enable-all: true
  disable:
    - cyclop
    - gocyclo
    - gochecknoglobals
    - godot
    - err113
    - exhaustive
    - funlen
    - ireturn
    - interfacebloat
    - maintidx
    - nilnil
    - nlreturn
    - nolintlint
    - perfsprint
    - prealloc
    - revive
    - nonamedreturns
    - tagalign
    - testpackage
    - tagliatelle
    - wsl
    - dupl
    - exhaustruct
    - nestif
    - paralleltest
    - varnamelen
    - wrapcheck
    - lll
    - godox

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - linters:
      - govet
      text: "(copies lock)"
    - linters:
      - forbidigo
      text: "(fmt.Print(|f|ln)|print|println)"
    - linters:
      - gomoddirectives
      text: "replacement are not allowed"
    - linters:
      - gocritic
      text: "paramTypeCombine"
    - linters:
      - mnd
      text: "Magic number: 0o6"
    - linters:
      - gocritic
      text: "(sloppyReassign: re-assignment to `err`|may want to add detail)"
    - linters:
      - gosec
      text: "G204"
    - path: _test\.go
      linters:
        - lll
        - dupl
        - goconst

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes: github.com/terranvigil/dynamic-crf

service:
  golangci-lint-version: 2.11.3
